baseURL = "https://arnab7070.github.io/"
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25

theme         = "BlogRa"
languageCode  = "en-us"
title         = "Code World"

disqusShortname = ""

[params]
    description     = "The Ultimate Tech Website"
    contactEmail    = "anonymous1638@gmail.com"
    footer          = "© Copyright 2022 CodeWorld"
    googleSearch    = ""
    googleAnalytics = ""      # Google Analytics v4
    adsense         = "pub-5270518167259467"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page
    ignoreTaxonomies = ["*"]

    # Social Media Params
    facebook   = "https://www.facebook.com/arnab7070"
    twitter    = ""
    youtube    = ""
    instagram  = "https://www.instagram.com/arnab7070"
    github     = "https://github.com/arnab7070"
    pinterest  = ""
    linkedin   = "https://www.linkedin.com/in/arnab7070/"


# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4
    
    [[menu.main]]
        identifier = "about"
        name = "About Us"
        weight = 3
            [[menu.main]]
                parent = "about"
                name = "About"
                url = "/about/"
                weight = 1
            [[menu.main]]
                parent = "about"
                name = "Privacy Policy"
                url = "/privacy/"
                weight = 2
            [[menu.main]]
                parent = "about"
                name = "DMCA"
                url = "/dmca/"
                weight = 3
            [[menu.main]]
                parent = "about"
                name = "Terms & Conditions"
                url = "/terms/"
                weight = 4

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 4

[markup.goldmark.parser.attribute]
    block = true

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.102.3"
