name: Hugo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: actions/setup-hugo@v1
        with:
          hugo-version: '0.78.2'
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-hugo@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
